repos:
  - repo: local
    hooks:
      - id: nix-format
        name: nixfmt
        entry: nixfmt
        language: system
        files: "\\.nix$"
      - id: nix-flake-check
        name: nix flake check
        entry: nix flake check
        language: system
        pass_filenames: false
